-- 일정 v3: 색상 / 하이라이트 / 2부 / 설명
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS color TEXT DEFAULT 'green';
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS highlight BOOLEAN DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS time2 TEXT;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS title2 TEXT;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS type2 TEXT;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS description TEXT;
